#Perceptron: Simple logic OR



In [3]:
import numpy as np

data = np.array( [[0,0],[0,1],[1,0],[1,1]] )
target_y = np.array( [[0],[1],[1],[1]] )
# print( data )
# print( target_y )

n_neuron = 1
n_iteration = 250
learning_rate = .01
threshold = 0

n_data , n_features = data.shape
# print(n_data , n_features)

bias = 0 - np.ones((n_data, 1))
# print(bias)

###  np.concatenate( (to whom, who),  axis= col or row)
data = np.concatenate( (bias, data),  axis=1)
n_features += 1

print(data, data.shape, n_features)

### weights >>> generally we use small positive values
n_weights = n_features * n_neuron

## first generate weights 
weights = np.random.uniform( -1, 1, n_weights)
# print(weights)

## convert the weights array to vector accordint to the number of features
weights = np.reshape( weights, (n_features, n_neuron) )
print("\nWeights: \n",weights, weights.shape)

[[-1.  0.  0.]
 [-1.  0.  1.]
 [-1.  1.  0.]
 [-1.  1.  1.]] (4, 3) 3

Weights: 
 [[0.35364077]
 [0.09830936]
 [0.69638039]] (3, 1)


In [6]:
for t in range(n_iteration):
    
    weighted_sum = np.matmul( data, weights )
    ## [ n_data X n_features ] * [n_features X n_neuron]
    
    ## get output using threshold and change them to 1 or 0
    output = (weighted_sum > threshold) * 1
    
    result_diff = output - target_y

    for k in range(n_data):
        for i in range(n_features):
            for j in range(n_neuron):
                weights[i, j] -= learning_rate * result_diff[k, j] * data[k, i] 
    
    # if t%10 == 0:
    #     print("\n\nIteration", t)
    #     print("Weights: \n",weighted_sum)
    #     print("\nOutputs: \n",output)
    #     print( "\n Diff , y - t ", result_diff)
    #     print( "\nNew Weights\n", weights ) 

(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)
(4, 1)

##Task: update weights using matrix operations


##Task: use the "Learnt" model i.e. set of weights to predict new data