In [ ]:
from sklearn.datasets  import load_iris
import matplotlib.pyplot as plt

In [ ]:
iris = load_iris()
print(type(iris), "\n ",type(iris.data))
# print(iris.data)

n_sample, n_features = iris.data.shape
print(n_sample, n_features)
print(iris.target)
print(iris.target_names)


## slicing
print(iris.data[:10])

<class 'sklearn.utils.Bunch'> 
  <class 'numpy.ndarray'>
150 4
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


#Decision Tree from sklearn

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.model_selection import cross_val_score

DT_classifier_model = DecisionTreeClassifier(  )
print(DT_classifier_model)


DT_classifier_model.fit( iris.data, iris.target )

prediction = DT_classifier_model.predict(iris.data)

score = cross_val_score( DT_classifier_model, iris.data, iris.target, cv=5 )
print(score)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
[0.96666667 0.96666667 0.9        1.         1.        ]
